<?php if (!$error && $message) : ?>
    <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true"><i
                        class="notika-icon notika-close"></i></span></button> <?php echo $message; ?>
    </div>
<?php elseif ($error && $message): ?>
    <div class="alert alert-danger alert-dismissible alert-mg-b-0" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true"><i
                        class="notika-icon notika-close"></i></span></button> <?php echo $message; ?>
    </div>
<?php endif; ?>
<div class="form-element-area">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="form-element-list">
                    <div class="basic-tb-hd">
                        <h2>User Add</h2>
                    </div>
                    <div class="row">
                        <form method="POST">
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                                <div class="form-group">
                                    <div class="nk-int-st">
                                        <input type="text" name="username" class="form-control" placeholder="Username">
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                                <div class="form-group">
                                    <div class="nk-int-st">
                                        <input type="text" name="password" class="form-control" placeholder="Password">
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                                <div class="form-group">
                                    <select name="role" class="form-control">
                                        <option value="1">Admin</option>
                                        <option value="0">Moderator</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                                <div class="form-group">
                                    <div class="nk-int-st">
                                        <button type="submit" class="btn btn-primary btn-sm hec-button waves-effect">
                                            Save
                                        </button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <center>
            <?php include APPLICATION_PATH . "/../vendor/jasongrimes/paginator/examples/pager.phtml"; ?>
        </center>
        <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="form-element-list">
                    <div class="basic-tb-hd">
                        <h2>User List</h2>
                    </div>
                    <?php foreach ($result as $r): ?>
                        <div class="row">
                            <form method="POST">
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                                    <div class="form-group">
                                        <div class="nk-int-st">
                                            <input type="text" name="username" class="form-control"
                                                   placeholder="Username" value="<?php echo $r->getUsername(); ?>">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                                    <div class="form-group">
                                        <div class="nk-int-st">
                                            <input type="text" name="password" class="form-control"
                                                   placeholder="Password">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                                    <div class="form-group">
                                        <select name="role" class="form-control">
                                            <?php foreach ([0 => 'Moderator', 1 => 'Admin'] as $roleKey => $role): ?>
                                                <option value="<?php echo $roleKey; ?>" <?php echo $roleKey == $r->getRole() ? 'selected' : ''; ?>><?php echo $role; ?></option>
                                            <?php endforeach; ?>
                                        </select>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                                    <div class="form-group">
                                        <div class="nk-int-st">
                                            <button type="submit"
                                                    class="btn btn-primary btn-sm hec-button waves-effect">Update
                                            </button>
                                        </div>
                                    </div>
                                </div>
                                <input type="hidden" name="id" value="<?php echo $r->getId(); ?>">
                            </form>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
</div>
